// app/tabs/(riders)/presentation/styles/ActiveDeliveryPage.styles.ts
import { StyleSheet } from "react-native";

const MAP_TOP_HEIGHT = 420;

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: "#F5F5F5",
  },
  safeArea: {
    flex: 1,
    backgroundColor: "#F5F5F5",
  },
  mapArea: {
    flex: 1,
    overflow: "hidden",
    minHeight: 420,
  },
  mapImage: {
    width: "100%",
    height: "100%",
  },
  etaBadgeOverlay: {
    position: "absolute",
    top: 100,
    left: 0,
    right: 0,
    alignItems: "center",
    zIndex: 10,
  },
  turnByTurnOverlay: {
    position: "absolute",
    bottom: 8,
    left: 12,
    right: 12,
    zIndex: 10,
  },
  topBar: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    minHeight: 84,
    borderBottomLeftRadius: 26,
    borderBottomRightRadius: 26,
    backgroundColor: "#CEEDB2",
    paddingHorizontal: 14,
    paddingTop: 14,
    paddingBottom: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  avatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#C9C9C9",
  },
  topBarTextWrap: {
    flex: 1,
  },
  topBarName: {
    fontFamily: "StackSansHeadline_700Bold",
    fontSize: 12,
    color: "#101010",
  },
  topBarNumber: {
    fontFamily: "StackSansHeadline_500Medium",
    fontSize: 10,
    color: "#101010",
    marginTop: 1,
  },
  topBarActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
  },
  headerActionButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: "#A7DD89",
    alignItems: "center",
    justifyContent: "center",
  },
  mapRightControls: {
    position: "absolute",
    top: 92,
    right: 12,
    alignItems: "center",
    gap: 8,
  },
  etaBadge: {
    backgroundColor: "rgba(57, 76, 113, 0.85)",
    borderRadius: 9,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  etaBadgeText: {
    fontFamily: "StackSansHeadline_700Bold",
    fontSize: 8,
    color: "#FFFFFF",
  },
  mapControlButton: {
    width: 70,
    height: 70,
    borderRadius: 35,
    backgroundColor: "rgba(0, 0, 0, 0.78)",
    alignItems: "center",
    justifyContent: "center",
  },
  bottomSheet: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "#ffffff",
    borderTopLeftRadius: 34,
    borderTopRightRadius: 34,
  },
  sheetHandleArea: {
    alignItems: "center",
    paddingTop: 8,
    paddingBottom: 8,
  },
  sheetHandle: {
    width: 45,
    height: 4,
    borderRadius: 2,
    backgroundColor: "#D0D0D0",
  },
  phasePillRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 24,
    marginTop: 2,
    marginBottom: 12,
  },
  phasePill: {
    flex: 1,
    minHeight: 26,
    borderRadius: 13,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 8,
  },
  phasePillActive: {
    backgroundColor: "#33975E",
  },
  phasePillInactive: {
    backgroundColor: "#E0E0E0",
  },
  phasePillText: {
    fontFamily: "StackSansHeadline_700Bold",
    fontSize: 8,
    color: "#A2A2A2",
    textAlign: "center",
  },
  phasePillTextActive: {
    color: "#FFFFFF",
  },
  sheetBody: {
    paddingHorizontal: 24,
    paddingBottom: 120,
  },
  badgeWrap: {
    alignSelf: "flex-start",
    backgroundColor: "#8A774A",
    borderRadius: 8,
    paddingHorizontal: 7,
    paddingVertical: 2,
  },
  badgeText: {
    fontFamily: "StackSansHeadline_700Bold",
    fontSize: 8,
    color: "#FFFFFF",
  },
  mainTargetName: {
    marginTop: 10,
    fontFamily: "StackSansHeadline_700Bold",
    fontSize: 13,
    color: "#141414",
  },
  locationRow: {
    marginTop: 4,
    marginBottom: 12,
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 4,
  },
  baseText: {
    fontFamily: "StackSansHeadline_500Medium",
    fontSize: 8,
    color: "#1B1B1B",
    lineHeight: 13,
  },
  sectionLabel: {
    marginBottom: 8,
    fontFamily: "StackSansHeadline_400Regular",
    fontSize: 8,
    color: "#7A7A7A",
    letterSpacing: 0.3,
  },
  checkboxGroup: {
    gap: 10,
  },
  checkboxRow: {
    minHeight: 28,
    borderRadius: 14,
    backgroundColor: "#DEDEDE",
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  captureButton: {
    marginTop: 18,
    minHeight: 78,
    borderRadius: 16,
    backgroundColor: "#DCDCDC",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
  },
  captureButtonCompact: {
    minHeight: 72,
  },
  captureButtonText: {
    fontFamily: "StackSansHeadline_700Bold",
    fontSize: 13 / 2,
    color: "#087434",
    letterSpacing: 0.8,
  },
  phaseTransitionOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.25)",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 24,
  },
  phaseTransitionCard: {
    width: "100%",
    maxWidth: 220,
    backgroundColor: "#FFFFFF",
    borderRadius: 14,
    paddingVertical: 14,
    paddingHorizontal: 14,
    alignItems: "center",
    gap: 8,
  },
  phaseTransitionText: {
    fontFamily: "StackSansHeadline_700Bold",
    fontSize: 11,
    color: "#1E1E1E",
  },
});
