// app/tabs/(riders)/presentation/styles/index.styles.ts
import { fontFamily, fontWeight } from "@/constants/FontTheme";
import { useColors } from "@/hooks/useColors";
import { StyleSheet } from "react-native";

export const stylesFactory = (colors: ReturnType<typeof useColors>) =>
  StyleSheet.create({
    screen: {
      flex: 1,
      backgroundColor: colors.background,
    },
    safeArea: {
      flex: 1,
      backgroundColor: colors.background,
    },
    scrollContent: {
      paddingBottom: 12,
    },
    header: {
      backgroundColor: colors.primaryContainer,
      borderBottomLeftRadius: 27,
      borderBottomRightRadius: 27,
      paddingHorizontal: 24,
      paddingTop: 10,
      paddingBottom: 18,
      minHeight: 122,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    logo: {
      width: 120,
      height: 38,
    },
    dutyRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
    },
    dutyLabel: {
      fontFamily: fontFamily.semiBold,
      fontWeight: fontWeight.semiBold,
      fontSize: 12,
      color: colors.textDark,
      letterSpacing: 0.2,
    },
    dutySwitch: {
      transform: [{ scaleX: 0.84 }, { scaleY: 0.84 }],
    },
    autoAcceptRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      backgroundColor: colors.card,
      marginHorizontal: 14,
      marginTop: 12,
      paddingHorizontal: 16,
      paddingVertical: 12,
      borderRadius: 16,
    },
    autoAcceptInfo: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      flex: 1,
    },
    autoAcceptTitle: {
      fontFamily: fontFamily.semiBold,
      fontWeight: fontWeight.semiBold,
      fontSize: 14,
      color: colors.text,
    },
    autoAcceptDesc: {
      fontFamily: fontFamily.regular,
      fontWeight: fontWeight.regular,
      fontSize: 11,
      color: colors.textMuted,
      marginTop: 2,
    },
    mapWrap: {
      width: "100%",
      height: 334,
      overflow: "hidden",
      position: "relative",
      backgroundColor: colors.backgroundMuted,
    },
    mapImage: {
      width: "100%",
      height: "100%",
    },
    activeMarkerWrap: {
      position: "absolute",
      left: "34%",
      top: "20%",
      alignItems: "center",
    },
    activeMarker: {
      width: 50,
      height: 50,
      borderRadius: 25,
      backgroundColor: colors.primary,
      borderWidth: 2,
      borderColor: colors.borderAccent,
      alignItems: "center",
      justifyContent: "center",
    },
    activeMarkerStem: {
      width: 4,
      height: 11,
      borderRadius: 3,
      backgroundColor: colors.white,
      marginTop: -1,
    },
    idleMarker: {
      position: "absolute",
      left: "43.5%",
      top: "35.5%",
      width: 58,
      height: 58,
      borderRadius: 16,
      backgroundColor: colors.white,
      alignItems: "center",
      justifyContent: "center",
      shadowColor: colors.black,
      shadowOpacity: 0.12,
      shadowRadius: 8,
      shadowOffset: { width: 0, height: 3 },
      elevation: 3,
    },
    driverDotOuter: {
      position: "absolute",
      left: "68.5%",
      top: "53%",
      width: 27,
      height: 27,
      borderRadius: 13.5,
      backgroundColor: colors.white,
      alignItems: "center",
      justifyContent: "center",
    },
    driverDotInner: {
      width: 17,
      height: 17,
      borderRadius: 8.5,
      backgroundColor: colors.info,
    },
    locateButton: {
      position: "absolute",
      right: 16,
      bottom: 14,
      width: 60,
      height: 60,
      borderRadius: 18,
      backgroundColor: colors.backgroundAccent,
      alignItems: "center",
      justifyContent: "center",
    },
    sheet: {
      backgroundColor: colors.background,
      paddingHorizontal: 14,
      paddingTop: 16,
    },
    sectionTitle: {
      fontFamily: fontFamily.bold,
      fontWeight: fontWeight.bold,
      fontSize: 13,
      color: colors.text,
      marginBottom: 11,
    },
    sectionTitleSecondary: {
      fontFamily: fontFamily.bold,
      fontWeight: fontWeight.bold,
      fontSize: 25 / 2,
      color: colors.text,
      marginBottom: 11,
      marginTop: 16,
    },
    orderCard: {
      backgroundColor: colors.white,
      borderRadius: 20,
      paddingHorizontal: 14,
      paddingTop: 10,
      paddingBottom: 12,
    },
    orderTopRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "flex-start",
    },
    priceText: {
      fontFamily: fontFamily.bold,
      fontWeight: fontWeight.bold,
      fontSize: 18,
      color: colors.primary,
    },
    expireWrap: {
      alignItems: "flex-end",
    },
    expireLabel: {
      fontFamily: fontFamily.medium,
      fontWeight: fontWeight.medium,
      fontSize: 9,
      color: colors.text,
      letterSpacing: 0.8,
    },
    expireValue: {
      marginTop: 1,
      fontFamily: fontFamily.bold,
      fontWeight: fontWeight.bold,
      fontSize: 9,
      color: colors.error,
      letterSpacing: 0.8,
    },
    recipientText: {
      marginTop: -2,
      fontFamily: fontFamily.bold,
      fontWeight: fontWeight.bold,
      fontSize: 7,
      color: colors.text,
    },
    routeRow: {
      marginTop: 6,
      flexDirection: "row",
      alignItems: "flex-start",
      gap: 6,
    },
    routeDot: {
      width: 7,
      height: 7,
      borderRadius: 3.5,
      marginTop: 4,
    },
    pickupDot: {
      backgroundColor: colors.text,
    },
    dropoffDot: {
      backgroundColor: colors.success,
    },
    routeMainText: {
      fontFamily: fontFamily.regular,
      fontWeight: fontWeight.regular,
      fontSize: 8,
      color: colors.text,
    },
    routeSubText: {
      marginTop: 1,
      fontFamily: fontFamily.regular,
      fontWeight: fontWeight.regular,
      fontSize: 6,
      color: colors.text,
    },
    ctaRow: {
      marginTop: 7,
      flexDirection: "row",
      justifyContent: "flex-end",
      alignItems: "center",
    },
    ctaPill: {
      height: 24,
      borderRadius: 20,
      alignItems: "center",
      justifyContent: "center",
    },
    ctaPillActive: {
      width: 156,
      backgroundColor: "rgba(8, 116, 52, 0.5)",
    },
    ctaPillInactive: {
      width: 156,
      backgroundColor: "rgba(207, 63, 63, 0.2)",
    },
    ctaArrowPill: {
      width: 30,
      height: 24,
      borderRadius: 20,
      alignItems: "center",
      justifyContent: "center",
      marginLeft: -4,
    },
    ctaArrowPillActive: {
      backgroundColor: colors.success,
    },
    ctaArrowPillInactive: {
      backgroundColor: colors.error,
    },
    ctaText: {
      fontFamily: fontFamily.bold,
      fontWeight: fontWeight.bold,
      fontSize: 8,
      letterSpacing: 0.8,
    },
    ctaTextActive: {
      color: colors.textDark,
    },
    ctaTextInactive: {
      color: colors.error,
    },
  });
