// app/tabs/(riders)/presentation/styles/RiderProfile.styles.ts
import { useColors } from "@/hooks/useColors";
import { StyleSheet } from "react-native";
import { fontFamily, fontWeight } from "@/constants/FontTheme";

export const stylesFactory = (colors: ReturnType<typeof useColors>) =>
  StyleSheet.create({
    screen: {
      flex: 1,
      backgroundColor: colors.background,
    },
    safeArea: {
      flex: 1,
      backgroundColor: colors.background,
    },
    scrollContent: {
      paddingBottom: 26,
    },
    headerSurface: {
      width: "100%",
      height: 176,
      borderBottomLeftRadius: 26,
      borderBottomRightRadius: 26,
      alignItems: "center",
      justifyContent: "flex-start",
      paddingTop: 8,
      backgroundColor: colors.primaryContainer,
    },
    menuButton: {
      position: "absolute",
      top: 16,
      right: 20,
      width: 28,
      height: 28,
      borderRadius: 14,
      justifyContent: "center",
      alignItems: "center",
    },
    avatarWithBadge: {
      width: 92,
      height: 92,
      position: "relative",
      marginTop: 6,
      marginBottom: 6,
    },
    avatar: {
      width: 92,
      height: 92,
      borderRadius: 46,
      backgroundColor: colors.backgroundMuted,
    },
    cameraBadge: {
      position: "absolute",
      right: 0,
      bottom: 0,
      width: 27,
      height: 27,
      borderRadius: 13.5,
      backgroundColor: colors.white,
      justifyContent: "center",
      alignItems: "center",
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
    },
    userName: {
      fontFamily: fontFamily.semiBold,
      fontWeight: fontWeight.semiBold,
      fontSize: 16,
      color: colors.text,
    },
    statsRow: {
      marginTop: 14,
      marginHorizontal: "4.6%",
      flexDirection: "row",
      justifyContent: "space-between",
      gap: 10,
    },
    statCard: {
      flex: 1,
      minHeight: 52,
      borderRadius: 14,
      backgroundColor: colors.backgroundMuted,
      alignItems: "center",
      justifyContent: "center",
    },
    statValue: {
      fontFamily: fontFamily.bold,
      fontWeight: fontWeight.bold,
      fontSize: 13,
      color: colors.text,
    },
    statLabel: {
      marginTop: 1,
      fontFamily: fontFamily.semiBold,
      fontWeight: fontWeight.semiBold,
      fontSize: 8,
      color: colors.textMuted,
    },
    promoCard: {
      marginTop: 16,
      marginHorizontal: "4.6%",
      borderRadius: 18,
      backgroundColor: "#40995F",
      paddingHorizontal: 16,
      paddingVertical: 13,
    },
    promoBadge: {
      position: "absolute",
      top: 10,
      right: 12,
      height: 22,
      borderRadius: 11,
      backgroundColor: colors.backgroundTint,
      justifyContent: "center",
      alignItems: "center",
      paddingHorizontal: 10,
    },
    promoBadgeText: {
      fontSize: 10,
      color: colors.primary,
      fontFamily: fontFamily.bold,
      fontWeight: fontWeight.bold,
    },
    promoLogo: {
      width: 120,
      height: 34,
      tintColor: colors.white,
    },
    promoSubtitle: {
      marginTop: 6,
      width: "80%",
      fontSize: 12,
      lineHeight: 16,
      color: colors.white,
      fontFamily: fontFamily.medium,
      fontWeight: fontWeight.medium,
      textAlign: "left",
    },
    garageWrap: {
      marginTop: 14,
      marginHorizontal: "4.6%",
      borderRadius: 12,
      backgroundColor: colors.backgroundSoft,
      borderWidth: 1,
      borderColor: colors.border,
      paddingHorizontal: 12,
      paddingTop: 10,
      paddingBottom: 10,
    },
    garageHeaderRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    garageTitle: {
      fontFamily: fontFamily.bold,
      fontWeight: fontWeight.bold,
      fontSize: 13,
      color: colors.textDark,
    },
    garagePagerContent: {
      width: "100%",
    },
    vehicleSlide: {
      width: 280,
      minHeight: 62,
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      paddingTop: 8,
      paddingBottom: 8,
    },
    vehicleIconCircle: {
      width: 34,
      height: 34,
      borderRadius: 17,
      backgroundColor: colors.backgroundMuted,
      alignItems: "center",
      justifyContent: "center",
    },
    vehicleTextWrap: {
      flex: 1,
    },
    vehicleTitle: {
      fontFamily: fontFamily.semiBold,
      fontWeight: fontWeight.semiBold,
      fontSize: 12,
      color: colors.text,
    },
    vehicleSubtitle: {
      marginTop: 2,
      fontFamily: fontFamily.medium,
      fontWeight: fontWeight.medium,
      fontSize: 8,
      color: colors.textMuted,
    },
    garageDotsRow: {
      marginTop: 2,
      marginBottom: 4,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 5,
    },
    garageDot: {
      width: 5,
      height: 5,
      borderRadius: 2.5,
      backgroundColor: colors.border,
    },
    garageDotActive: {
      backgroundColor: colors.success,
    },
    garageDivider: {
      height: 1,
      backgroundColor: "rgba(0, 0, 0, 0.12)",
      marginTop: 4,
      marginBottom: 8,
    },
    garageTagsRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
    },
    garageTag: {
      minHeight: 24,
      borderRadius: 12,
      backgroundColor: colors.backgroundAccent,
      paddingHorizontal: 10,
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
    },
    garageTagText: {
      fontFamily: fontFamily.semiBold,
      fontWeight: fontWeight.semiBold,
      fontSize: 10,
      color: colors.success,
    },
    sectionCard: {
      marginTop: 14,
      marginHorizontal: "4.6%",
      borderRadius: 12,
      backgroundColor: colors.backgroundSoft,
      borderWidth: 1,
      borderColor: colors.border,
      overflow: "hidden",
    },
    settingRow: {
      minHeight: 48,
      paddingHorizontal: 10,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    settingLeft: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      flex: 1,
    },
    settingIconCircle: {
      width: 26,
      height: 26,
      borderRadius: 13,
      backgroundColor: colors.successContainer,
      justifyContent: "center",
      alignItems: "center",
    },
    settingLabel: {
      fontSize: 11,
      color: colors.textDark,
      fontFamily: fontFamily.regular,
      fontWeight: fontWeight.regular,
    },
    logoutLabel: {
      fontSize: 11,
      color: colors.error,
      fontFamily: fontFamily.semiBold,
      fontWeight: fontWeight.semiBold,
    },
    settingRight: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      marginLeft: 12,
    },
    settingValue: {
      fontSize: 11,
      color: colors.textMuted,
      fontFamily: fontFamily.semiBold,
      fontWeight: fontWeight.semiBold,
    },
    switchRoleRow: {
      marginTop: 14,
      marginHorizontal: "4.6%",
      minHeight: 68,
      borderRadius: 14,
      backgroundColor: colors.backgroundSoft,
      borderWidth: 1,
      borderColor: colors.border,
      paddingHorizontal: 14,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    switchRoleLeft: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
    },
    switchRoleIconCircle: {
      width: 28,
      height: 28,
      borderRadius: 14,
      backgroundColor: colors.successContainer,
      justifyContent: "center",
      alignItems: "center",
    },
    switchRoleTitle: {
      fontSize: 13,
      color: colors.textDark,
      fontFamily: fontFamily.semiBold,
      fontWeight: fontWeight.semiBold,
    },
    switchRoleValue: {
      marginTop: 2,
      fontSize: 11,
      color: colors.textMuted,
      fontFamily: fontFamily.medium,
      fontWeight: fontWeight.medium,
    },
    modalBackdrop: {
      flex: 1,
      backgroundColor: "rgba(0, 0, 0, 0.35)",
      justifyContent: "flex-end",
    },
    modalSheet: {
      backgroundColor: colors.white,
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
      paddingTop: 18,
      paddingBottom: 28,
      paddingHorizontal: 18,
    },
    modalTitle: {
      fontSize: 16,
      color: colors.text,
      fontFamily: fontFamily.bold,
      fontWeight: fontWeight.bold,
      marginBottom: 12,
    },
    modalOptionsList: {
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.backgroundSubtle,
      overflow: "hidden",
    },
    modalOptionRow: {
      minHeight: 48,
      paddingHorizontal: 14,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: colors.border,
    },
    modalOptionRowLast: {
      borderBottomWidth: 0,
    },
    modalOptionText: {
      fontSize: 13,
      color: colors.textDark,
      fontFamily: fontFamily.medium,
      fontWeight: fontWeight.medium,
    },
    modalOptionTextSelected: {
      color: colors.success,
      fontFamily: fontFamily.bold,
      fontWeight: fontWeight.bold,
    },
  });
